server:
  port: 8082
spring:
  application:
    name: PageVoyage
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.10.218:3306/page_voyage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.10.241  # 本地Redis地址
      port: 6379       # 默认端口
      password: leadnews       # 没设密码就留空
      database: 1    # 默认数据库
      timeout: 3000ms

  kafka:
    bootstrap-servers: 192.168.10.241:9092
    producer:
      retries: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: ${spring.application.name}-test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    streams:
      application-id: article-hit-stream-app
      bootstrap-servers: 192.168.10.241:9092
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        replication.factor: 1
        num.stream.threads: 1
        processing.guarantee: exactly_once
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: INFO
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.streams: ERROR
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    me.yan: INFO

# DashScope 百炼平台配置
dashscope:
  api-key: sk-461e5aa0594146b7922b976f6da44903
  model: qwen-max
  max-tokens: 1500
  temperature: 0.7

